application: piwicasportfolio
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:


- url: /pde
  static_dir: pde

- url: /bower_components
  static_dir: bower_components









